apiVersion: skaffold/v2beta14
kind: Config
build:
  artifacts:
  - image: ghcr.io/shipperizer/iam-ext-authz
    sync:
      infer:
      - "cmd/*"
      - "main.go"
      - "pkg/*"
      - "internal/*"
      - "go.mod"
      - "go.sum"
    docker:
    
